#cloud-config

coreos:

    etcd:
        name     : coreos1
        discovery: https://discovery.etcd.io/7863b680910e37870334ae19594de26c
        addr     : 10.0.0.100:4001
        peer-addr: 10.0.0.100:7001

    fleet:
        public-ip: 10.0.0.100
        metadata : 'location=hist,public=true,name=coreos1,role=gainmaster'

    update:
        reboot-strategy: etcd-lock
        group          : stable

    units:
        - name   : etcd.service
          command: start

        - name   : fleet.service
          command: start

        - name   : rpc-statd.service
          command: start
          enable : true

        - name    : docker.socket
          command : start
          drop-ins: 
            - name: 30-ListenStream.conf
              content: |
                  [Socket]
                  ListenStream=10.0.0.100:2375

        - name   : mnt-shared.mount
          command: start
          content: |
              [Mount]
              What=10.0.0.20:/
              Where=/mnt/shared
              Type=nfs

hostname: coreos1

users:
    - name : tony
      gecos: Tony Hesjevik
      coreos-ssh-import-github: feskehau
      groups:
          - sudo
          - docker

    - name : andreas
      gecos: Andreas Hopen
      coreos-ssh-import-github: hopeeen
      groups:
          - sudo
          - docker

    - name : knut
      gecos: Knut Lorvik
      coreos-ssh-import-github: superlorre
      groups:
          - sudo
          - docker

write_files:
    - path       : /etc/systemd/network/public.network
      permissions: 0644
      owner      : root
      content    : |
          [Match]
          MACAddress=00:50:56:bb:2e:52
          [Network]
          Address=158.38.57.117/24
          Gateway=158.38.57.1
          DNS=158.38.50.10
          DNS=158.38.49.10

    - path       : /etc/systemd/network/private.network
      permissions: 0644
      owner      : root
      content    : |
          [Match]
          MACAddress=00:50:56:bb:43:75
          [Network]
          Address=10.0.0.100/24

    - path       : /etc/coreos_metadata
      permissions: 0644
      content    : |
          PUBLIC_IPV4=158.38.57.117
          PRIVATE_IPV4=10.0.0.100
          SHARED_DATA=/mnt/shared

    - path       : /etc/gainmaster_metadata
      permissions: 0644
      content    : |
          GAINMASTER_DOMAIN=hesjevik.im
          GAINMASTER_SKYDNS_DOMAIN_PATH=im/hesjevik

    - path       : /etc/conf.d/nfs
      permissions: '0644'
      content    : |
          OPTS_RPC_MOUNTD=""