#cloud-config

coreos:
  etcd:
    name: coreos3
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/7863b680910e37870334ae19594de26c
    addr: 10.0.0.102:4001       # For client communication
    peer-addr: 10.0.0.102:7001  # For server communication
  fleet:
    public-ip: 10.0.0.102
  update:
    reboot-strategy: etcd-lock
    group: stable
  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: rpc-statd.service
      command: start
      enable: true

    - name: mnt-shared.mount
      command: start
      content: |
        [Mount]
        What=10.0.0.20:/
        Where=/mnt/shared
        Type=nfs

    - name: skydns-register-coreos3.service
      command: start
      content: |
        [Unit]
        Description=Registers this servers DNS record in SkyDNS config

        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStart=/usr/bin/etcdctl set /skydns/im/hesjevik/coreos3 \
          '{"host":"158.38.57.119","ttl":3600}'
        Type=oneshot

    - name: registrator.service
      command: start
      content: |
        [Unit]
        Description=Registrator service

        Requires=etcd.service
        After=etcd.service

        Requires=docker.service
        After=docker.service

        [Service]
        ExecStartPre=-/usr/bin/docker kill registrator
        ExecStartPre=-/usr/bin/docker rm registrator
        ExecStart=/usr/bin/docker run --name registrator -d \
          -v /var/run/docker.sock:/tmp/docker.sock \
          -h coreos3 \
          gliderlabs/registrator skydns2:///hesjevik.im

        ExecStop=/usr/bin/docker stop registrator

hostname: coreos3

users:
  - name: tony
    gecos: Tony Hesjevik
    coreos-ssh-import-github: feskehau
    groups:
      - sudo
      - docker

  - name: andreas
    gecos: Andreas Hopen
    coreos-ssh-import-github: hopeeen
    groups:
      - sudo
      - docker

  - name: knut
    gecos: Knut Lorvik
    coreos-ssh-import-github: superlorre
    groups:
      - sudo
      - docker

write_files:
  - path: /etc/systemd/network/public.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:5b:6e

      [Network]
      Address=158.38.57.119/24
      Gateway=158.38.57.1
      DNS=158.38.50.10
      DNS=158.38.49.10

  - path: /etc/systemd/network/private.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:42:ed

      [Network]
      Address=10.0.0.102/24

  - path: /etc/metadata
    permissions: 0644
    content: |
      PUBLIC_IPV4=158.38.57.119
      PRIVATE_IPV4=10.0.0.102
      SHARED_DATA=/mnt/shared

  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""