#cloud-config

coreos:
  etcd:
    name: coreos1
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/7863b680910e37870334ae19594de26c
    addr: 10.0.0.100:4001       # For client communication
    peer-addr: 10.0.0.100:7001  # For server communication
  fleet:
    public-ip: 10.0.0.100
  update:
    reboot-strategy: etcd-lock
    group: stable
  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: rpc-statd.service
      command: start
      enable: true

    - name: mnt-shared.mount
      command: start
      content: |
        [Mount]
        What=10.0.0.20:/
        Where=/mnt/shared
        Type=nfs

    - name: skydns.service
      command: start
      content: |
        [Unit]
        Description=SkyDNS service

        Requires=etcd.service
        After=etcd.service

        Requires=docker.service
        After=docker.service

        [Service]
        TimeoutStartSec=0
        KillMode=none

        ExecStartPre=-/usr/bin/docker kill skydns
        ExecStartPre=-/usr/bin/docker rm skydns
        ExecStartPre=/usr/bin/docker pull skynetservices/skydns

        ExecStart=/usr/bin/docker run --rm --name skydns \
          -e "ETCD_MACHINES=http://10.0.0.100:4001" \
          -e "SKYDNS_ADDR=0.0.0.0:53" \
          -e "SKYDNS_DOMAIN=hesjevik.im" \
          -e "SKYDNS_NAMESERVERS=" \
          -p 53:53/udp \
          -p 53:53/tcp \
          --dns=127.0.0.1 \
          skynetservices/skydns

        ExecStop=/usr/bin/docker stop skydns

    - name: skydns-register-dns-ns.service
      command: start
      content: |
        [Unit]
        Description=Registers this server as NS in SkyDNS config

        Requires=etcd.service
        After=etcd.service

        [Service]
        ExecStart=/usr/bin/etcdctl set /skydns/im/hesjevik/dns/ns \
          '{"host":"158.38.57.117"}'
        Type=oneshot

    - name: docker.socket
      command: start
      drop-ins: 
    - name: 30-ListenStream.conf
      content: |
        [Socket]
        ListenStream=10.0.0.100:2375

hostname: coreos1

users:
  - name: tony
    gecos: Tony Hesjevik
    coreos-ssh-import-github: feskehau
    groups:
      - sudo
      - docker

  - name: andreas
    gecos: Andreas Hopen
    coreos-ssh-import-github: hopeeen
    groups:
      - sudo
      - docker

  - name: knut
    gecos: Knut Lorvik
    coreos-ssh-import-github: superlorre
    groups:
      - sudo
      - docker

write_files:
  - path: /etc/systemd/network/public.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:2e:52

      [Network]
      Address=158.38.57.117/24
      Gateway=158.38.57.1
      DNS=158.38.50.10
      DNS=158.38.49.10

  - path: /etc/systemd/network/private.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:43:75

      [Network]
      Address=10.0.0.100/24

  - path: /etc/metadata
    permissions: 0644
    content: |
      PUBLIC_IPV4=158.38.57.117
      PRIVATE_IPV4=10.0.0.100
      SHARED_DATA=/mnt/shared

  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""