#cloud-config

coreos:
  etcd:
    name: coreos3
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/7863b680910e37870334ae19594de26c
    addr: 10.0.0.102:4001       # For client communication
    peer-addr: 10.0.0.102:7001  # For server communication
  fleet:
    public-ip: 10.0.0.102
  update:
    reboot-strategy: etcd-lock
    group: stable
  units:
    - name: etcd.service
      command: start

    - name: fleet.service
      command: start

    - name: rpc-statd.service
      command: start
      enable: true

    - name: mnt-shared.mount
      command: start
      content: |
        [Mount]
        What=10.0.0.20:/
        Where=/mnt/shared
        Type=nfs

    - name: docker.socket
      command: start
      drop-ins: 
    - name: 30-ListenStream.conf
      content: |
        [Socket]
        ListenStream=10.0.0.102:2375

hostname: coreos3

users:
  - name: tony
    gecos: Tony Hesjevik
    coreos-ssh-import-github: feskehau
    groups:
      - sudo
      - docker

  - name: andreas
    gecos: Andreas Hopen
    coreos-ssh-import-github: hopeeen
    groups:
      - sudo
      - docker

  - name: knut
    gecos: Knut Lorvik
    coreos-ssh-import-github: superlorre
    groups:
      - sudo
      - docker

write_files:
  - path: /etc/systemd/network/public.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:5b:6e

      [Network]
      Address=158.38.57.119/24
      Gateway=158.38.57.1
      DNS=158.38.50.10
      DNS=158.38.49.10

  - path: /etc/systemd/network/private.network
    permissions: 0644
    owner: root
    content: |
      [Match]
      MACAddress=00:50:56:bb:42:ed

      [Network]
      Address=10.0.0.102/24

  - path: /etc/metadata
    permissions: 0644
    content: |
      PUBLIC_IPV4=158.38.57.119
      PRIVATE_IPV4=10.0.0.102
      SHARED_DATA=/mnt/shared

  - path: /etc/conf.d/nfs
    permissions: '0644'
    content: |
      OPTS_RPC_MOUNTD=""