#cloud-config

coreos:
  etcd:
    name: 21e-CoreOS1
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/c159128e20cc1a724a91d357e1391e30
    addr: 158.38.57.117:4001
    peer-addr: 10.0.0.100:7001
  fleet:
    public-ip: 158.38.57.117
  update:
    reboot-strategy: etcd-lock
    group: stable
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: public.network
      content: |
        [Match]
        MACAddress=00:50:56:bb:2e:52

        [Network]
        Address=158.38.57.117/24
        Gateway=158.38.57.1
        DNS=158.38.50.10
        DNS=158.38.49.10

    - name: private.network
      content: |
        [Match]
        MACAddress=00:50:56:bb:43:75

        [Network]
        Address=10.0.0.100/24

hostname: 21e-CoreOS1

users:
  - name: tony
    gecos: Tony Hesjevik
    coreos-ssh-import-github: feskehau
    groups:
      - sudo
      - docker

  - name: andreas
    gecos: Andreas Hopen
    coreos-ssh-import-github: hopeeen
    groups:
      - sudo
      - docker

  - name: knut
    gecos: Knut Lorvik
    coreos-ssh-import-github: superlorre
    groups:
      - sudo
      - docker